replicaCount: 1

image:
  repository: nginx
  pullPolicy: IfNotPresent
  tag: "1.21"

service:
  type: ClusterIP
  port: 80

# Vault path for secrets
vault:
  path: secret/data/kv/test
  # Example: secret/data/myapp/database
