{{- if .Values.pgpool.vault.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.names.fullname" . }}-pgpool
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
  annotations:
    avp.kubernetes.io/path: "{{ .Values.pgpool.vault.path }}"
    {{- if .Values.commonAnnotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
type: Opaque
stringData:
  # Pgpool admin password
  admin-password: <admin-password>
  # SR check user password
  sr-check-password: <sr-check-password>
{{- end }}
