{{- if .Values.postgresql.vault.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.names.fullname" . }}-postgresql
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
  annotations:
    avp.kubernetes.io/path: "{{ .Values.postgresql.vault.path }}"
    {{- if .Values.commonAnnotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
type: Opaque
stringData:
  # PostgreSQL main user password
  password: <password>
  # PostgreSQL postgres superuser password
  postgres-password: <postgres-password>
  # Replication manager password
  repmgr-password: <repmgr-password>
{{- end }}
