apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  annotations:
    avp.kubernetes.io/path: "{{ .Values.vault.path }}"
type: Opaque
stringData:
  # AVP will replace these placeholders with values from Vault
  username: <username>
  password: <password>
  database: <database>
  api-key: <api-key>
