apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ include "cluster.clusterName" . }}
spec:
  instances: {{ .Values.cluster.instances }}
  imageName: {{ .Values.cluster.imageName }}
  imagePullPolicy: {{ .Values.cluster.imagePullPolicy }}

  superuserSecret:
    name: {{ .Values.superuser.secret | default (printf "%s-superuser" (include "cluster.clusterName" .)) }}

  bootstrap:
    initdb:
      database: {{ .Values.database.name }}
      owner: {{ .Values.database.owner }}
      secret:
        name: {{ .Values.database.secret | default (printf "%s-app" (include "cluster.clusterName" .)) }}

  storage:
    {{- if .Values.storage.storageClass }}
    storageClass: {{ .Values.storage.storageClass }}
    {{- end }}
    size: {{ .Values.storage.size }}

  {{- with .Values.resources }}
  resources:
    {{- toYaml . | nindent 4 }}
  {{- end }}

  {{- if .Values.postgresql.parameters }}
  postgresql:
    parameters:
      {{- range $key, $value := .Values.postgresql.parameters }}
      {{ $key }}: {{ $value | quote }}
      {{- end }}
  {{- end }}

  {{- if .Values.monitoring.enabled }}
  monitoring:
    enablePodMonitor: {{ .Values.monitoring.enabled }}
  {{- end }}

  {{- if .Values.backup.enabled }}
  backup:
    retentionPolicy: {{ .Values.backup.retentionPolicy | quote }}
    barmanObjectStore:
      destinationPath: {{ .Values.backup.barmanObjectStore.destinationPath }}
      s3Credentials:
        accessKeyId:
          name: {{ .Values.backup.barmanObjectStore.s3Credentials.accessKeyId.name }}
          key: {{ .Values.backup.barmanObjectStore.s3Credentials.accessKeyId.key }}
        secretAccessKey:
          name: {{ .Values.backup.barmanObjectStore.s3Credentials.secretAccessKey.name }}
          key: {{ .Values.backup.barmanObjectStore.s3Credentials.secretAccessKey.key }}
      wal:
        compression: {{ .Values.backup.barmanObjectStore.wal.compression }}
  {{- end }}
