{{- if and .Values.backup.enabled .Values.scheduledBackup.enabled }}
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: {{ .Values.scheduledBackup.name | default (printf "%s-backup" (include "cluster.clusterName" .)) }}
spec:
  schedule: {{ .Values.scheduledBackup.schedule | quote }}
  backupOwnerReference: self
  cluster:
    name: {{ include "cluster.clusterName" . }}
{{- end }}
