{{- if not .Values.superuser.secret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cluster.clusterName" . }}-superuser
type: kubernetes.io/basic-auth
data:
  username: {{ .Values.superuser.username | b64enc | quote }}
  {{- if .Values.superuser.password }}
  password: {{ .Values.superuser.password | b64enc | quote }}
  {{- else }}
  password: {{ randAlphaNum 32 | b64enc | quote }}
  {{- end }}
{{- end }}
---
{{- if not .Values.database.secret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cluster.clusterName" . }}-app
type: kubernetes.io/basic-auth
data:
  username: {{ .Values.database.username | b64enc | quote }}
  {{- if .Values.database.password }}
  password: {{ .Values.database.password | b64enc | quote }}
  {{- else }}
  password: {{ randAlphaNum 32 | b64enc | quote }}
  {{- end }}
{{- end }}
